select
    gt.dt
    , gt.company_id
    , gt.loan_id
    , gt.loan_reference_number
    , gt.is_bundled
    , gt.product
    , gt.currency
    , gt.country_code
    , gt.business_address
    , gt.principal_disbursed
    , gt.principal_amount_due
    , gt.interest_amount_due
    , gt.vat_fee_tax_amount_due
    , gt.vat_amount_due
    , gt.fee_amount_due
    , gt.tax_amount_due
    , gt.payment_amount
    , gt.adjustment_amount
    , gt.loc_allocation_toward_principal
    , gt.loc_allocation_toward_interest
    , gt.loc_allocation_toward_vat_fee_tax
    , gt.loc_allocation_toward_vat
    , gt.loc_allocation_toward_fee
    , gt.loc_allocation_toward_tax
    , gt.payment_toward_principal
    , gt.payment_toward_interest
    , gt.payment_toward_vat_fee_tax
    , gt.payment_toward_vat
    , gt.payment_toward_fee
    , gt.payment_toward_tax
    , gt.adjustment_toward_principal
    , gt.adjustment_toward_interest
    , gt.adjustment_toward_vat_fee_tax
    , gt.adjustment_toward_vat
    , gt.adjustment_toward_fee
    , gt.adjustment_toward_tax
    , gt.overpay_toward_principal
    , gt.overpay_toward_interest
    , gt.overpay_toward_vat_fee_tax
    , gt.overpay_toward_vat
    , gt.overpay_toward_fee
    , gt.overpay_toward_tax
    , gt.total_obligation_principal
    , gt.total_obligation_interest
    , gt.total_obligation_vat_fee_tax
    , gt.total_obligation_vat
    , gt.total_obligation_fee
    , gt.total_obligation_tax
    , gt.cumulative_invoiced_principal
    , gt.cumulative_invoiced_interest
    , gt.cumulative_invoiced_vat_fee_tax
    , gt.cumulative_invoiced_vat
    , gt.cumulative_invoiced_fee
    , gt.cumulative_invoiced_tax
    , gt.uninvoiced_principal
    , gt.uninvoiced_interest
    , gt.uninvoiced_vat_fee_tax
    , gt.uninvoiced_vat
    , gt.uninvoiced_fee
    , gt.uninvoiced_tax
    , gt.balance
    , gt.principal_balance
    , gt.interest_balance
    , gt.vat_fee_tax_balance
    , gt.vat_balance
    , gt.fee_balance
    , gt.tax_balance
    , gt.overpay_balance
    , gt.spot_rate
    , gt.principal_disbursed_usd
    , gt.principal_amount_due_usd
    , gt.interest_amount_due_usd
    , gt.vat_fee_tax_amount_due_usd
    , gt.vat_amount_due_usd
    , gt.fee_amount_due_usd
    , gt.tax_amount_due_usd
    , gt.payment_amount_usd
    , gt.adjustment_amount_usd
    , gt.loc_allocation_toward_principal_usd
    , gt.loc_allocation_toward_interest_usd
    , gt.loc_allocation_toward_vat_fee_tax_usd
    , gt.loc_allocation_toward_vat_usd
    , gt.loc_allocation_toward_fee_usd
    , gt.loc_allocation_toward_tax_usd
    , gt.payment_toward_principal_usd
    , gt.payment_toward_interest_usd
    , gt.payment_toward_vat_fee_tax_usd
    , gt.payment_toward_vat_usd
    , gt.payment_toward_fee_usd
    , gt.payment_toward_tax_usd
    , gt.adjustment_toward_principal_usd
    , gt.adjustment_toward_interest_usd
    , gt.adjustment_toward_vat_fee_tax_usd
    , gt.adjustment_toward_vat_usd
    , gt.adjustment_toward_fee_usd
    , gt.adjustment_toward_tax_usd
    , gt.overpay_toward_principal_usd
    , gt.overpay_toward_interest_usd
    , gt.overpay_toward_vat_fee_tax_usd
    , gt.overpay_toward_vat_usd
    , gt.overpay_toward_fee_usd
    , gt.overpay_toward_tax_usd
    , gt.balance_usd
    , gt.principal_balance_usd
    , gt.interest_balance_usd
    , gt.vat_fee_tax_balance_usd
    , gt.vat_balance_usd
    , gt.fee_balance_usd
    , gt.tax_balance_usd
    , gt.overpay_balance_usd
    , gt.forex_adjustment
    , gt.total_obligation_principal_usd
    , gt.total_obligation_interest_usd
    , gt.total_obligation_vat_fee_tax_usd
    , gt.total_obligation_vat_usd
    , gt.total_obligation_fee_usd
    , gt.total_obligation_tax_usd
    , gt.cumulative_invoiced_principal_usd
    , gt.cumulative_invoiced_interest_usd
    , gt.cumulative_invoiced_vat_fee_tax_usd
    , gt.cumulative_invoiced_vat_usd
    , gt.cumulative_invoiced_fee_usd
    , gt.cumulative_invoiced_tax_usd
    , gt.uninvoiced_principal_usd
    , gt.uninvoiced_interest_usd
    , gt.uninvoiced_vat_fee_tax_usd
    , gt.uninvoiced_vat_usd
    , gt.uninvoiced_fee_usd
    , gt.uninvoiced_tax_usd
    , gt.cumulative_debits_due
    , gt.cumulative_debits
    , gt.cumulative_credits
    , gt.is_current
    , gt.delinquent_dt
    , gt.dq_bucket_daily
    , gt.dq_bucket_monthly
    , gt.days_past_due
    , gt.charge_off_4_months_dt
    , gt.charge_off_120_days_dt
    , gt.charge_off_exclusion
    , gt.charge_off_dt
    , gt.charge_off_flag
    , gt.is_in_repayment
    , gt.repayment_dt
    , gt.first_cms_rpp_issue_dt
    , gt.status
    , gt.company_charge_off_dt
    , gt.is_out_of_policy_repayment
from
    capital_markets_dm.gwc_tape gt
where
    gt.dt = '{}'
    and gt.loan_reference_number like 'RPP%'
